name: Build
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - id: package
        name: Create nupkg
        run: |
          pip install PyYAML requests
          python3 choco.py

      - name: Install nscp
        uses: crazy-max/ghaction-chocolatey@v3
        with:
          args: |
            install nscp --debug --verbose ${{ steps.package.outputs.choco_pre_flag }}--source .

      - name: Basic nscp test
        run: |
          & 'C:\Program Files\NSClient++\nscp.exe' settings --show

      - name: Push package
        uses: crazy-max/ghaction-chocolatey@v3
        if: github.ref == 'refs/heads/main'
        with:
          args: |
            push ${{ steps.package.outputs.nupkg_filename }} --source https://push.chocolatey.org/ --key ${{ secrets.CHOCO_API_TOKEN }}
