name: Publish
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: read

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - id: package
        name: Create nupkg
        run: |
          pip install PyYAML requests
          python3 choco.py

      - name: Push package
        uses: crazy-max/ghaction-chocolatey@v4
        with:
          args: |
            push ${{ steps.package.outputs.nupkg_filename }} --source https://push.chocolatey.org/ --key ${{ secrets.CHOCO_API_TOKEN }} --skip-duplicate
